############################
# STEP 1 build executable binary
############################
FROM arm64v8/golang:1.14-alpine3.11 AS builder

RUN apk update && apk add --no-cache git
RUN apk --no-cache add ca-certificates
WORKDIR /src
ADD go.mod /src
ADD go.sum /src
# Fetch dependencies.
RUN go mod download

ADD *.go /src/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -ldflags="-w -s" -o main craigslistWatcher.go

############################
# STEP 2 build a small image
############################
FROM scratch
# Copy our static executable.
COPY --from=builder /src/main /go/bin/main
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

ENV GITHUB_TOKEN="{{GITHUB_TOKEN}}"
ENV SLACK_WEBHOOK="{{SLACK_WEBHOOK}}"
# Run the main binary.
ENTRYPOINT [ "/go/bin/main" ] 